### ISSUE TITLE
The mvm robot will still gain the ability to modify the cvar reload even if it is invalid

### ISSUE THREAD

**Issue by zyox123cc** [JugadorXEI/tf2rebalance_jug#5]
ROBOT Still get "character" (not weapon) attributes

**Comment by JugadorXEI** [comment]
I'll make this cvar-controllable soon.

**Comment by JugadorXEI** [comment]
Fixed in https://github.com/JugadorXEI/tf2rebalance_jug/commit/7c8adf1c8cdc1600be6b5d7812eb0e4d809ca6ed
You can get the release here: https://github.com/JugadorXEI/tf2rebalance_jug/releases/tag/1.8.2

**Comment by zyox123cc** [comment]
nice
